version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run: echo "This step is build"
      - run:
          name: "build artifact"
          command: |
            echo "this is artifact 1. by $CIRCLE_TAG" > memo1.txt
            echo "this is artifact 2. by $CIRCLE_TAG" > memo2.txt
            zip artifact.zip memo1.txt memo2.txt
      - store_artifacts:
          path: ./artifact.zip
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - artifact.zip
  deploy:
    docker:
      - image: ubuntu:16.04
    steps:
      - run: echo "This step is deploy"
      - attach_workspace:
        at: /tmp/artifacts
      - run:
          name: "install tools."
          command: |
            apt-get update
            apt-get install -y curl jq
      - run:
          name: "deploy to GitHub Release."
          command: |
            GITHUB_RELEASE_ID=`curl -s https://${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}@api.github.com/repos/katoys/ci-test/releases/tags/${CIRCLE_TAG} | jq '.["id"]'`
            curl -s \
              -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" \
              -H "Content-Type: application/zip" \
              --data-binary @/tmp/artifacts/artifact.zip \
              https://uploads.github.com/repos/katoys/ci-test/releases/${GITHUB_RELEASE_ID}/assets?name=artifact.zip | jq

workflows:
  version: 2
  test-workflow:
    jobs:
      - build:
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
