version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "This step is build"
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "This step is test"
  approve:
    type: approval
  deploy:
    requires:
      - approve
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "This step is deploy"
