version: 2

jobs:
  build:
    docker:
      - image: busybox:latest
    steps:
      - run: echo "This step is build"
  test:
    docker:
      - image: busybox:latest
    steps:
      - run: echo "This step is test"
  deploy:
    docker:
      - image: busybox:latest
    steps:
      - run: echo "This step is deploy"

workflows:
  version: 2
  test-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - hold
          filters:
            tags:
              only: /^.*/
