version: 2

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "This step is build"
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "This step is test"
  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "This step is deploy"

workflows:
  version: 2
  test-workflow:
    jobs:
      build:
      test:
        requires:
          - build
      hold:
        type: approval
        requires:
          - test
      deploy:
        requires:
          - hold
