version: 2

jobs:
  build:
    docker:
      - image: busybox:latest
    steps:
      - run: echo "This step is build"
  test:
    docker:
      - image: busybox:latest
    steps:
      - run: echo "This step is test"
  deploy:
    filter:
      tags:
        only: /^.*/
      branches:
        ignore: /.*/
    docker:
      - image: busybox:latest
    steps:
      - run: echo "This step is deploy"

workflows:
  version: 2
  test-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
